spring:
  application:
    name: @name@
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: redis
    port: 6379
springdoc:
  swagger-ui:
    path: /swagger-ui
logging:
  level:
    org:
      springframework:
        cache: TRACE
